from typing import List, Optional, Protocol
from product import Product

class ProductStoreInterface(Protocol):
    def get_latest_products(self, count: int) -> List[Product]: ...
    def search(self, keyword: str) -> List[Product]: ...
    def filter(self, products: List[Product], brand: Optional[str], max_price: Optional[int]) -> List[Product]: ...
    def get_detail(self, product_id: int) -> Optional[Product]: ...